[tool.mypy]
python_version = 3.9
warn_unused_configs = true
strict = true
show_error_codes = true
show_column_numbers = true
warn_no_return = false
no_implicit_optional = false
follow_imports = 'skip'

[tool.black]
line-length = 110
target-version = ['py310']
include = '\.pyi?$'
